### ISSUE TITLE
The morphing tool does not work well with EnderIO’s Yeta Wrench

### ISSUE THREAD

**Issue by ghost** [VazkiiMods/Morph-o-Tool#38]
If you use the mode where you can only see one specific type of conduit, it glitches out when you use the morphing tool.

GIF: https://gfycat.com/FickleDistantAdouri

**Comment by PapiDimmi** [comment]
@Vazkii This is the only reason I don’t use the morphing tool.

Can you please consider fixing this?

This GitHub page seems pretty inactive, by the way.

**Comment by 64Hz** [comment]
Same issue for me. Exact same.

Sorry for the hassle on this @Vazkii . Great mod though!

**Comment by shader301202** [comment]
I've got the same issue.

**Comment by Dimentive** [comment]
I’m having the same issue.

![2019-03-23_19 33 22](https://user-images.githubusercontent.com/34230933/54870115-a3396880-4da2-11e9-9c74-4eb7b2f93375.png)

When you use the Yeta Wrench and use the scroll wheel while holding shift, you switch through different modes, which makes certain types of conduits near-invisible, but this seemingly works when doing so with the Morph-o-Tool too, even if you don’t have it morphed to the Yeta Wrench. This could be solved by letting players use a key bind to manually morph the Morph-o-Tool, rather than mouse scrolling and holding shift.

**Minecraft version:** 1.12.2
**Forge version:** 14.23.5.2781
**Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version 1.62, latest)
**Morph-o-Tool version:** 1.2-21 (latest)
**AutoRegLib version:** 1.3-2 (latest)

**Comment by MoreThanHidden** [comment]
Looking at a ender io machine and scrolling will fix you issue in the meantime.

**Comment by Dimentive** [comment]
Don’t you have to hold shift too, which manually morphs the tool as well?
If not, that’s a good workaround, although it would be great if this could be fixed.

Nevertheless, I love the mod. It’s super convenient!

**Comment by SullySadface** [comment]
There's a keybind in EnderIO to cycle the Yeta Wrench view, it defaults to Y.
