### ISSUE TITLE
[Suggestion] Shift+scroll tool switching alternative.

### ISSUE THREAD

**Issue by eyeonus** [VazkiiMods/Morph-o-Tool#51]
Machine Muse's Modular Power Suits used the Shift+Scroll method to change the active tool on the Power Fist, and it was found to interfere with other uses of the Shift key, such as in Creative-mode flight, pressing Shift causes downward motion, which might not be what was intended when building a multi-block machine in mid-air, for example.

Nowadays, active tool switching in MPS is done by holding down the hotbar key for the slot the Power Fist is in, which opens a radial menu while the key is held down, and selecting the desired tool by highlighting it with the mouse and releasing the hotbar key, which is IMO cooler visually, but more importantly doesn't overlap with any common controls.

**Comment by MoreThanHidden** [comment]
Shift + Space negates the creative falling, can also set the tool as required before flight or use on the original mode. But yes as an improvement a GUI and/or mode switch key could be a config option.  Doesn't conflict with a tools shift+scroll options if looking at a block from that mod.

**Comment by DoomRater** [comment]
No takers in over a year?  That's amazing.  Alright, I'm forking, but be warned- I'm shooting for 1.12.2.  I also want to lift the one tool from one mod limitation while I'm at it, since manual activation makes this trivial to select.  It would also bring it in line with the Akashic Tome.

**Comment by Jack-McKalling** [comment]
Considering that the issue is described in this report, I want to bring up the crouch issue again.
If you're _forced_  to crouch by a slab over your head, the tool effectively traps the selected hotbar slot. This is incorrect behaviour altogether.

The tool's switching mechanic should be listening to the actual crouch _control_ being used, rather than being crouched directly. Now that there is a forced-crouch situation in the vanilla game.

A similar problem was described (and fixed!) here: CyclopsMC/IntegratedDynamics/issues/1064

**Comment by Uraneptus** [comment]
This issue is very old but most likely still relevant. I will consider changing the way the tool can be chosen. I will open a new issue for that!
